feat: vulnerability location
Ostorlab/agent_nmap pull request #49
Opened 2022-10-19 10:11 UTC by SmileOstorlab

2022-10-19 14:38 UTC, deadly-panda submitted a review, later dismissed
Remember to add unit tests.

2022-10-19 14:38 UTC, deadly-panda commented on agent/nmap_agent.py
> +            res = scan_results.get('nmaprun', {}).get('host', {}).get('address', '')
The name res is confusing

2022-10-19 14:38 UTC, deadly-panda commented on agent/nmap_agent.py
> +                                              metadata=[],
If you have the port add it in the meta data.

2022-10-19 14:38 UTC, deadly-panda commented on agent/nmap_agent.py
> +                                              asset=ipv4.IPv4(host=res.get('@addr', ''), mask=port)
mask=port ?

2022-10-19 14:38 UTC, deadly-panda commented on agent/nmap_agent.py
> +            else:
elif ipv6

2022-10-19 14:38 UTC, deadly-panda commented on agent/nmap_agent.py
> +            else:
I don't see the case for the domain target ? In that case you should emit the hostname as a domain asset.

2022-10-20 10:40 UTC, 3asm requested changes

2022-10-20 10:40 UTC, 3asm commented on agent/nmap_agent.py
> +            res = scan_results.get('nmaprun', {}).get('host', {}).get('address', '')
res for addres?

2022-10-20 10:40 UTC, 3asm commented on agent/nmap_agent.py
> +            if res.get('@addrtype', '') == 'ipv4':
worth putting in a variable.

2022-10-20 10:40 UTC, 3asm commented on agent/nmap_agent.py
> +                                              metadata=[],
metadata is empty!

2022-10-20 10:40 UTC, 3asm commented on agent/nmap_agent.py
> +                                              metadata=[],
metadata is also empty.

2022-10-20 10:40 UTC, 3asm commented on agent/nmap_agent.py
> +                                          ))
NO UNIT TEST!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2022-10-21 01:54 UTC, 3asm requested changes

2022-10-21 01:54 UTC, 3asm commented on agent/nmap_agent.py
> +                                          ))
I still don't see any unit test checking for the values in vulnerability location.

2022-10-24 11:17 UTC, 3asm requested changes

2022-10-24 11:17 UTC, 3asm commented on agent/nmap_agent.py
> +from ostorlab.assets import ipv4, ipv6, domain_name
I think it would be cleaner to use domain_name_asset and keep the variable name as is.

2022-10-24 15:53 UTC, 3asm approved these changes

2022-10-24 15:53 UTC, 3asm approved these changes

2022-10-24 15:53 UTC, merged