Refactor unit tests to use fixtures.
Ostorlab/agent_nmap pull request #65
Opened 2023-02-06 14:25 UTC by deadly-panda

2023-02-06 15:57 UTC, mohsinenar requested changes

2023-02-06 15:57 UTC, mohsinenar commented on tests/conftest.py
> +@pytest.fixture(scope="function", name="nmap_test_agent")
why the scope is a function?

2023-02-06 15:57 UTC, mohsinenar commented on tests/conftest.py
> +@pytest.fixture(scope="function")
same.

2023-02-06 17:14 UTC, deadly-panda commented on tests/conftest.py
> +@pytest.fixture(scope="function", name="nmap_test_agent")
Just being explicit.

2023-02-07 07:50 UTC, mohsinenar approved these changes

2023-02-07 09:49 UTC, merged