Update from python3.10 to 3.11
Ostorlab/agent_nmap pull request #78
Opened 2023-10-31 11:14 UTC by elyousfi5

2023-10-31 13:51 UTC, 3asm requested changes

2023-10-31 13:51 UTC, 3asm commented on requirement.txt
> +async_timeout
Is this needed?

2023-10-31 15:53 UTC, oussamaessaji commented
You need to build the agent locally do not rely only on unit tests!!

2023-11-02 17:54 UTC, 3asm submitted a review, later dismissed

2023-11-02 17:54 UTC, 3asm commented on ostorlab.yaml
> +version: 0.9.3
```suggestion
version: 0.10.0
```

2023-11-03 03:37 UTC, 3asm approved these changes

2023-11-03 03:37 UTC, merged