Add top ports to agent nmap
Ostorlab/agent_nmap pull request #80
Opened 2023-12-05 16:13 UTC by BlueSquare1

2023-12-05 16:30 UTC, amine3 requested changes

2023-12-05 16:30 UTC, amine3 commented on agent/nmap_options.py
> +    top_ports: Optional[int] | None = None
int | None = None What does the Optional do here?

2023-12-05 16:30 UTC, amine3 commented on agent/nmap_options.py
> +            return ["--top-ports", str(self.top_ports)]
if top_ports has the same syntax as ports, ["--top-ports", self.top_ports] would work no?

2023-12-05 17:07 UTC, 3asm requested changes

2023-12-05 17:07 UTC, 3asm commented on tests/configs/top_ports.yaml
> +kind: Agent
What is this file?

2023-12-05 17:07 UTC, 3asm commented on tests/configs/fast_mode.yaml
> +kind: Agent
What is this file?

2023-12-05 17:07 UTC, 3asm commented on tests/configs/all_ports.yaml
> +kind: Agent
What is this file?

2023-12-05 17:07 UTC, 3asm commented on agent/nmap_wrapper.py
> +    def construct_command_host(self, host: str, mask: int) -> List[str]:
Why has this become public?

2023-12-05 17:07 UTC, 3asm commented on tests/nmap_wrapper_test.py
> +    [["top_ports.yaml"]],
This is not how we test the config, because those files are not maintainable, you should pass the config instead.

2023-12-05 17:27 UTC, BlueSquare1 commented on agent/nmap_wrapper.py
> +    def construct_command_host(self, host: str, mask: int) -> List[str]:
it's part of the test.

2023-12-06 13:26 UTC, 3asm commented on tests/conftest.py
> +            args=[],
I would set it explicitly to avoid changes in default settings.

2023-12-06 13:27 UTC, 3asm commented on tests/nmap_wrapper_test.py
> +    assert "-p" not in command
assert on the full command.

2023-12-06 13:27 UTC, 3asm commented on tests/nmap_wrapper_test.py
> +    assert "--top-ports" not in command
Assert on the full command.

2023-12-06 15:04 UTC, 3asm approved these changes

2023-12-06 15:07 UTC, merged